### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by Slian22** [Rhythmicc/jav#1]
jav info ssis-444
[错误] 出现错误: list indices must be integers or slices, not str
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packa │
│ ges/jav/__init__.py:276 in wrapper                                           │
│                                                                              │
│   273 │   │   │   │   │   ],                                                 │
│   274 │   │   │   │   │   title=(                                            │
│   275 │   │   │   │   │   │   "[bold green]✔[/]"                             │
│ ❱ 276 │   │   │   │   │   │   if checkExist(designation)                     │
│   277 │   │   │   │   │   │   else "[bold red]◯[/]"                          │
│   278 │   │   │   │   │   )                                                  │
│   279 │   │   │   │   │   + " "                                              │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packa │
│ ges/jav/__init__.py:170 in checkExist                                        │
│                                                                              │
│   167                                                                        │
│   168                                                                        │
│   169 def checkExist(designation):                                           │
│ ❱ 170 │   movie_path = config.select("movie_path")                           │
│   171 │   cmd = f'fd -i --type f --extension mp4 {designation} {movie_path[" │
│   172 │   if ssh := make_ssh_connect(movie_path):                            │
│   173 │   │   _, stdout, _ = ssh.exec_command(cmd)                           │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packa │
│ ges/jav/__config__.py:115 in select                                          │
│                                                                              │
│   112 │   def select(self, key):                                             │
│   113 │   │   if key not in self.config:                                     │
│   114 │   │   │   if key in problems:                                        │
│ ❱ 115 │   │   │   │   self.update(key, _ask(problems[key]))                  │
│   116 │   │                                                                  │
│   117 │   │   return self.config.get(key, None)                              │
│   118                                                                        │
│                                                                              │
│ /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packa │
│ ges/QuickProject/__config__.py:169 in _ask                                   │
│                                                                              │
│   166 │   │   │   │   return res                                             │
│   167 │                                                                      │
│   168 │   if "name" not in question:                                         │
│ ❱ 169 │   │   question["name"] = "NoName"                                    │
│   170 │   QproDefaultStatus.stop()                                           │
│   171 │   return ask()                                                       │
│   172                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: list indices must be integers or slices, not str

**Comment by Rhythmicc** [comment]
已修，更新下试试～

**Comment by Slian22** [comment]
Lovely.
